### ISSUE TITLE
interop with KeePassRPC

### ISSUE THREAD

**Issue by r2evans** [JanisEst/KeePassQuickUnlock#28]
Cool addition, I use it on Keepass2Android too.

When I installed v2.4, I get a failing popup (sometimes twice) from KeePass during plugin compile:

> ERROR! Please click on this box, press CTRL-C on your keyboard and paste into a new post on the KeeFox forum (http://keefox.org/help/forum). Doing this will help other people to use KeeFox without any unexpected error messages like this. Please briefly describe what you were doing when the problem occurred, which version of KeeFox, KeePass and Firefox you use and what other security software you run on your machine. Thanks! Technical detail follows: System.NullReferenceException: Object reference not set to an instance of an object.
>
>   at KeePassRPC.KeePassRPCClientConnection.Encrypt(String plaintext)
>
>   at KeePassRPC.KeePassRPCClientConnection.Signal(Signal signal, String methodName)

After I click through that, QU appears to work fine.

It seems intermittent, but the only common element to every time it fails is that KPQU and KPRPC are both being compiled. (I've gone through multiple repeats of the combinations of one, the other, and both, purging the two `Plugins` files and `PluginCache` dirs each time.)

Versions:
- win10
- Keepass-2.38
- KeeAgent-0.9.1.0
- KeePassQRCodeView-1.0.3.2
- KeePassQuickUnlock-2.4.0.0
- KeePassRPC-1.7.2.0
- KeeTrayTOTP-0.9.1

**Comment by JanisEst** [comment]
That's an error message from KeePassRPC, I don't know what's not working for them. I use QuickUnlock 2.4 and KeePassRPC 1.7.3 while writing this and I have never seen this error.

**Comment by r2evans** [comment]
I recognize the error is from that plugin, but since I also never got the error (before trying this plugin), I wonder (and defer to those more knowledgeable in the related code) if QU is perhaps triggering something. It's a minor point, more for historical purposes perhaps, since both seem to operate even after that popup.

Thanks for the plugin, JanisEst, it's quite nice so far!

**Comment by JanisEst** [comment]
Is there a reason why you use KeePassRPC 1.7.2? The current version is 1.7.3. Maybe there your error is fixed.

**Comment by r2evans** [comment]
Because [the only change](https://github.com/kee-org/keepassrpc/issues/5) was minor enough that I skipped it and have not revisited. I can certainly report back if I see it there, too, but it *sounds* like that change is unrelated. I'll let you know.

**Comment by JanisEst** [comment]
But the linked issue shows exactly your error message which should be fixed in 1.7.3.
